const people = [
  {
    name: "Walter White",
    street: "308 Negra Arroyo Lane",
    city: "Albuquerque",
    state: "New Mexico",
    country: "United States",
    nickname: "Heisenberg",
    birthday: "September 7, 1958",
    imageURL: "https://upload.wikimedia.org/wikipedia/en/thumb/0/03/Walter_White_S5B.png/220px-Walter_White_S5B.png",
  },
  {
    name: "Skyler White",
    street: "308 Negra Arroyo Lane",
    city: "Albuquerque",
    state: "New Mexico",
    country: "United States",
    nickname: "Sky",
    birthday: "August 11, 1970",
    imageURL: "https://upload.wikimedia.org/wikipedia/en/thumb/f/fb/Skyler_White_S5B.png/220px-Skyler_White_S5B.png",
  },
  {
    name: "Jesse Bruce Pinkman",
    city: "Albuquerque",
    state: "New Mexico",
    country: "United States",
    nickname: "Jess",
    birthday: "September 24, 1984",
    imageURL: "https://static.wikia.nocookie.net/breakingbad/images/9/95/JesseS5.jpg",
  },
  {
    name: "Gustavo Fring",
    city: "Albuquerque",
    state: "New Mexico",
    country: "United States",
    nickname: "Gus",
    birthday: "Unknown",
    imageURL: "https://static.wikia.nocookie.net/villains/images/1/1f/BCS_S4_Gustavo_Fring.jpg",
  }
];
